version: '2'
services:
  shadowsocks:
    container_name: shadowsocksr_shadowsocks-libev
    restart: always
    image: solidfd/ssr
    dns:
    - 8.8.8.8
    - 4.4.4.4
    ports:
    - "220:22"
    - "8080:8080"
    - "189:189"
